global:
    resolve_timeout: 1m

route:
  group_by: ['namespace','job']
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5m
  receiver: 'gmail-notifications'
  routes:
    - match:
        severity: critical
      receiver: gmail-notifications
receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: 'canigetyourinfo@gmail.com'
    from: 'bob.pt2991@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: bob.pt2991@gmail.com
    auth_identity: bob.pt2991@gmail.com
    auth_password: secretstring
    send_resolved: true
    require_tls: true